### PR TITLE
Update syntax to v0.6+, drop v0.5 support

### PR DESCRIPTION
**Pull request by andyferris**
I'm trying to update a bunch of packages for v0.7 compatibility. 

This package isn't seeing a lot of action relevant to v0.5.

### CODE REVIEW

**Comment by c42f** [comment]
Works for me!  BTW, you could have tried just dropping 0.5 from the `REQURE`.  FemtoCleaner would have done almost all the rest for you ;-)

**Comment by andyferris** [comment]
> you could have tried just dropping 0.5 from the REQURE

Oh, I get it! I had missed that part... I wondered why it worked on some packages and not others.

**Comment by c42f** [comment]
Hah, slack is spoiling me with endless emoticon support. I just keep wanting to use :heavy_check_mark: as a "reaction" on github.

**Comment by andyferris** [comment]
Oh yeah, its amazing how useful it is to be able to add that much nuance to a conversation. They are really onto something there, I feel.

**Pull request merged**
