### PR TITLE
Create Project.toml

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by asinghvi17** [comment]
This will make the package `dev`able on 1.4.  I kind of want to try and integrate GeometryTypes with this, it shouldn't be too hard at all...

**Comment by c42f** [comment]
Thanks! Looks like you need an `[extras]` section for the tests?

**Comment by asinghvi17** [comment]
Yep, looks like I forgot that.  Thanks!

**Comment by c42f** [comment]
Tests have failed still. Looks like you also need `ForwardDiff` in extras. I also suggest removing REQURE and test/REQURE as those will be obsolete.

**Comment by asinghvi17** [comment]
CI is green...LGTM from my end!

**Comment by mcabbott** [comment]
Came here to fix this, but you did it first! 

However something still seems weird, as 0.5.0 is not listed here, and what is listed has tighter bounds on Compat.jl, which was causing me problems:

https://github.com/JuliaRegistries/General/blob/master/C/CoordinateTransformations/Compat.toml

Perhaps it needs to be re-registered?

**Comment by asinghvi17** [comment]
Yeah, we should change bounds in the registry

**Comment by mcabbott** [comment]
Or simply release 0.5.1, I guess.

**Comment by c42f** [comment]
Yes, we should upgrade it to a new version 0.5.1.

Would be nice to aim for a 1.0 actually. Glancing over the issues, there's only #25 which really obviously needs something done about it.

**Comment by mcabbott** [comment]
That issue indeed looks close. But even if you do 1.0 tomorrow, it would be nice for 0.5.1 to exist with reasonable bounds, I think.

**Comment by c42f** [comment]
Absolutely agreed, I'll try to arrange 0.5.1.

**Pull request merged**
