### PR TITLE
Julia v0.7 fixes

### PR DESCRIPTION
**Pull request by slmcbane**
The only change needed was to add `atan2` to the imports from Compat. I also disallowed failures on nightly for Travis.

### CODE REVIEW

**Comment by andyferris** [comment]
Thanks!

**Comment by andyferris** [comment]
Wait... so this leaves deprecation warnings on v0.7.

`Compat` intends for code written in v0.6 code to use the v0.7 conventions and syntax - it's a "looking forward" approach. What we need to do is `using Compat` and start using `atan(y, x)` directly.

**Comment by slmcbane** [comment]
You're right. Why does Compat expose the old syntax in newer versions? It seems like it would make more sense to only supply the new syntax to older versions and not vice versa.

**Comment by andyferris** [comment]
No idea, to be honest?

**Pull request merged**
